$ANSIBLE_VAULT;1.1;AES256
30643635316536363136326661616166643932303339613539383661653161653135653335336534
6363643134653063323732653861623465326638323735620a393262373933626535336333643631
65353136343537313365663030303539653831366535373630386330316131646234346432396166
3038653863336562350a623366393238333039393338666165346261363861383134313230393038
34333938356534616333393936616338366637356464306463386637656234306131663534386534
61363963323236653932346433356662663466336137353964613338336636643031613362653735
66653265666434646235376135363035633836633631623363306661666231623636646337326437
35663939353364616663366635643163623735373932386632346266663862336661656261323535
66373864343933356565626430643166623666373163373163653139633465386630323130313334
39626364356135343734316138353233303163616234663933643439366435373835393435326264
66633064613464363764386161343434306431383462343733623533613761303962363638323734
65613162303962396131613832653034323639313936626565346334613939613566656462613735
66383763396164646533333433363634616130366563613331393237646637623761363738363633
37313333613465663464336632343466396165633263346364633536613863613235666133343763
35646634306265663365636133346462343532313130376562333833616266316535346665303066
35653866623163653163366430333138633430656164633034386262383262353335306364343339
34306537353033386132326563306562336264643635636534633238373339663338386465663562
31643961373166323366383036346261353663646432653864666362363534623533306464653966
39383162656166343732373232663261316137306639326330373539623463343439356333353837
66353361356235316338613735666339663138303761616135666265656539613034623137653933
6234
