- name: Deploy Nextcloud with OSS as main storage
  hosts: nextcloud-ecs
  become: true


  vars_files:
    - vars/main.yml

  roles:  
    - docker_setup
    - docker_app
    - Nextcloud
    - OSS
    - join_ad
